# Generated by Django 5.1.6 on 2025-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
